[project]
name = "MetaX"
version = "1.0.0"
authors = [
  { name="Qing Wu", email="author@example.com" },
]
description = "A tools to link Taxa and Functions in metaproteomics."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/byemaxx"
"Bug Tracker" = "https://github.com/byemaxx/MetaX/issues"