# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\max\OneDrive - University of Ottawa\code\TaxaFunc\MetaX\utils\MetaX_GUI\Setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(695, 405)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(Settings)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 677, 333))
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_auto_check_update = QtWidgets.QCheckBox(self.page)
        self.checkBox_auto_check_update.setChecked(True)
        self.checkBox_auto_check_update.setObjectName("checkBox_auto_check_update")
        self.gridLayout_2.addWidget(self.checkBox_auto_check_update, 0, 0, 1, 1)
        self.radioButton_update_stable = QtWidgets.QRadioButton(self.page)
        self.radioButton_update_stable.setChecked(True)
        self.radioButton_update_stable.setObjectName("radioButton_update_stable")
        self.gridLayout_2.addWidget(self.radioButton_update_stable, 0, 1, 1, 1)
        self.radioButton_update_beta = QtWidgets.QRadioButton(self.page)
        self.radioButton_update_beta.setObjectName("radioButton_update_beta")
        self.gridLayout_2.addWidget(self.radioButton_update_beta, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 677, 333))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.checkBox_auto_check_update.setText(_translate("Settings", "Auto Check Update"))
        self.radioButton_update_stable.setText(_translate("Settings", "Stable"))
        self.radioButton_update_beta.setText(_translate("Settings", "Beta"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Settings", "General"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Settings", "Others"))
