name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: false
        default: 'none'
        type: choice
        options:
          - 'none'
          - 'patch'
          - 'minor'
          - 'major'
      dry_run:
        description: 'Dry run (build only, do not publish)'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine==6.0.1
        
    - name: Update version if requested
      if: ${{ github.event.inputs.version_bump != 'none' }}
      run: |
        python -c "
        import re
        
        # Read current version
        with open('metax/utils/version.py', 'r') as f:
            content = f.read()
        
        # Extract current version
        version_match = re.search(r'__version__ = \'([^\']+)\'', content)
        if not version_match:
            raise ValueError('Could not find version in file')
        
        current_version = version_match.group(1)
        major, minor, patch = map(int, current_version.split('.'))
        
        # Bump version based on input
        bump_type = '${{ github.event.inputs.version_bump }}'
        if bump_type == 'major':
            major += 1
            minor = 0
            patch = 0
        elif bump_type == 'minor':
            minor += 1
            patch = 0
        elif bump_type == 'patch':
            patch += 1
        
        new_version = f'{major}.{minor}.{patch}'
        
        # Update version file
        new_content = re.sub(
            r'__version__ = \'[^\']+\'',
            f'__version__ = \'{new_version}\'',
            content
        )
        
        with open('metax/utils/version.py', 'w') as f:
            f.write(new_content)
        
        print(f'Updated version from {current_version} to {new_version}')
        "
        
    - name: Show current version
      run: |
        python -c "
        with open('metax/utils/version.py', 'r') as f:
            print('Current version file content:')
            print(f.read())
        "
        
    - name: Build package
      run: |
        python -m build
        
    - name: Check package
      run: |
        twine check dist/*
        
    - name: List built files
      run: |
        echo "Built files:"
        ls -la dist/
        echo "Package contents:"
        python -c "
        import os
        for file in os.listdir('dist'):
            if file.endswith('.whl') or file.endswith('.tar.gz'):
                print(f'  - {file}')
        "
        
    - name: Debug workflow inputs
      run: |
        echo "Workflow inputs:"
        echo "  version_bump: ${{ github.event.inputs.version_bump }}"
        echo "  dry_run: ${{ github.event.inputs.dry_run }}"
        echo "Conditions:"
        echo "  version_bump != 'none': ${{ github.event.inputs.version_bump != 'none' }}"
        echo "  dry_run != 'true': ${{ github.event.inputs.dry_run != 'true' }}"
        
    - name: Commit version update
      if: ${{ github.event.inputs.version_bump != 'none' && github.event.inputs.dry_run != 'true' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add metax/utils/version.py
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          VERSION=$(python -c 'import sys; sys.path.insert(0, "metax/utils"); from version import __version__; print(__version__)')
          git commit -m "Bump version to $VERSION"
          git push
        fi
        
    - name: Create Git tag
      if: ${{ github.event.inputs.version_bump != 'none' && github.event.inputs.dry_run != 'true' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        VERSION=$(python -c 'import sys; sys.path.insert(0, "metax/utils"); from version import __version__; print(__version__)')
        echo "Creating tag for version: $VERSION"
        # Check if tag already exists
        if git rev-parse "v$VERSION" >/dev/null 2>&1; then
          echo "Tag v$VERSION already exists, skipping tag creation"
        else
          git tag -a "v$VERSION" -m "Release version $VERSION"
          git push origin "v$VERSION"
        fi
        
    - name: Check PyPI token
      if: ${{ github.event.inputs.dry_run != 'true' }}
      run: |
        if [ -z "${{ secrets.PYPI_API_TOKEN }}" ]; then
          echo "❌ ERROR: PYPI_API_TOKEN secret is not set"
          exit 1
        else
          echo "✅ PYPI_API_TOKEN is configured"
        fi
        
    - name: Publish to PyPI
      if: ${{ github.event.inputs.dry_run != 'true' }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "Publishing to PyPI..."
        twine upload dist/* --verbose
        echo "✅ Successfully published to PyPI"
        
    - name: Dry run summary
      if: ${{ github.event.inputs.dry_run == 'true' }}
      run: |
        echo "🏃‍♂️ DRY RUN COMPLETED"
        echo "✅ Package built successfully"
        echo "✅ Package validation passed"
        echo "ℹ️  To publish for real, run this workflow again with 'Dry run' unchecked"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
        retention-days: 30
